In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv('train.csv')
train_df.head(1)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  

[1 rows x 785 columns]

In [25]:
train_df = pd.read_csv('train.csv')
train_df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
5          0       0       0       0       0       0       0       0       0   
6          7       0       0       0       0       0       0       0       0   
7          3       0       0       0       0       0       0       0       0   
8          5       0       0       0       0       0       0       0       0   
9          3       0       0       0       0       0       0       0       0   
10         8       0       0       0       0       0       0       0       0   
11         9       0       0       0       0       0       0       0       0   
12         1       0       0       0       0       0       0       0       0   
13         3       0       0       0       0       0       0       0       0   
14         3       0       0       0       0       0       0       0       0   
15         1       0       0       0       0       0       0       0       0   
16         2       0       0       0       0       0       0       0       0   
17         0       0       0       0       0       0       0       0       0   
18         7       0       0       0       0       0       0       0       0   
19         5       0       0       0       0       0       0       0       0   
20         8       0       0       0       0       0       0       0       0   
21         6       0       0       0       0       0       0       0       0   
22         2       0       0       0       0       0       0       0       0   
23         0       0       0       0       0       0       0       0       0   
24         2       0       0       0       0       0       0       0       0   
25         3       0       0       0       0       0       0       0       0   
26         6       0       0       0       0       0       0       0       0   
27         9       0       0       0       0       0       0       0       0   
28         9       0       0       0       0       0       0       0       0   
29         7       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970      2       0       0       0       0       0       0       0       0   
41971      3       0       0       0       0       0       0       0       0   
41972      4       0       0       0       0       0       0       0       0   
41973      4       0       0       0       0       0       0       0       0   
41974      3       0       0       0       0       0       0       0       0   
41975      9       0       0       0       0       0       0       0       0   
41976      2       0       0       0       0       0       0       0       0   
41977      4       0       0       0       0       0       0       0       0   
41978      4       0       0       0       0       0       0       0       0   
41979      4       0       0       0       0       0       0       0       0   
41980      7       0       0       0       0       0       0       0       0   
41981      2       0       0       0       0       0       0       0       0   
41982      8       0       0       0       0       0       0       0       0   
41983      7       0       0       0       0       0       0       0       0   
41984      3       0       0       0       0       0       0       0       0   
41985      3       0       0       0       0       0       0       0       0   
41986      0       0       0       0       0       0       0       0       0   
41987      5       0       0       0       0       0       0       0       0   
41988  

In [1]:
train_df.head(3)

NameError: name 'train_df' is not defined

In [2]:
load('ex3data1.mat')

ValueError: '(ex3data1.mat)' was not found in history, as a file, url, nor in the user namespace.

In [3]:
import scipy.io
scipy.io.loadmat('ex3data1.mat')

{'X': array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 'y': array([[10],
        [10],
        [10],
        ..., 
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [4]:
X

NameError: name 'X' is not defined

In [5]:
import scipy.io
mat = scipy.io.loadmat('ex3data1.mat')

In [6]:
mat.X


AttributeError: 'dict' object has no attribute 'X'

In [7]:
mat

{'X': array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 'y': array([[10],
        [10],
        [10],
        ..., 
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [8]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [9]:
a = np.array([1,2,3,4])

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a = np.array([1,2,3,4],[5,6,7,89])

TypeError: data type not understood

In [12]:
a

array([1, 2, 3, 4])

In [1]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_df.head(1)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  

[1 rows x 785 columns]

In [2]:
import pandas as pd
test_df = pd.read_csv('test.csv')
test_df.head(1)

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  

[1 rows x 784 columns]

In [3]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()

AttributeError: 'DataFrame' object has no attribute 'Values'

In [4]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ..., 
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]])

In [5]:
len(train_m[0])

785

In [6]:
len(train_m[:][0])

785

In [7]:
len(train_m[0][:])

785

In [8]:
len(train_m[0][4])

TypeError: object of type 'numpy.int64' has no len()

In [9]:
train_m[0][4]

0

In [10]:
train_m[0][9]

0

In [11]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m[5][784]

0

In [12]:
a = np.matrix([[1, 2], [3, 4],[5,6],[8,9]])a

NameError: name 'np' is not defined

In [13]:
import numpy as np
a = np.matrix([[1, 2], [3, 4],[5,6],[8,9]])
a

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [8, 9]])

In [14]:
a[0][3]

IndexError: index 3 is out of bounds for axis 0 with size 1

In [15]:
a[0][1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [16]:
a.Shape

AttributeError: 'matrix' object has no attribute 'Shape'

In [17]:
a

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [8, 9]])

In [18]:
a.shape

(4, 2)

In [19]:
a[0][1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [20]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m.shape

(42000, 785)

In [21]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m.shape[0]

42000

In [22]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m.shape[1]

785

In [23]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m[42000][0]

IndexError: index 42000 is out of bounds for axis 0 with size 42000

In [24]:
import pandas as pd
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m[41999][0]

9

In [26]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
train_m[0,:]

array([  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 188, 255,  94,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0, 191, 250, 253,  93,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [27]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:,1:]
y = train_m[:,0]

In [28]:
y.shape

(42000,)

In [29]:
X.shape

(42000, 784)

In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:,1:]
y = train_m[:,0]
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[‐1,:]),iris.target[‐1]))

In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:,1:]
y = train_m[:,0]
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[‐1,:]),iris.target[‐1]))

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:500,1:]
y = train_m[:500,0]
logistic = LogisticRegression()
logistic.fit(X,y)
#print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[‐1,:]),iris.target[‐1]))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:5,1:]
y = train_m[:5,0]
y

array([1, 0, 1, 4, 0])

In [3]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [4]:
X[3,:]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 220, 179,   6,   0,   0,   0,   0,   0,   0,   0,
         0,   9,  77,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  28, 247,  17,   0,   0,   0,   

In [5]:
len(X[3,:])

784

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data[:‐1,:], iris.target[:‐1]

SyntaxError: invalid character in identifier (<ipython-input-6-06d5c854fb73>, line 3)

In [7]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data[:-1,:], iris.target[:-1]

In [8]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[‐1,:]),iris.target[‐1]))
print('Probabilities for each class from 0 to 2: %s'% logistic.predict_proba(iris.data[‐1,:]))

SyntaxError: invalid character in identifier (<ipython-input-10-df833ec328f8>, line 4)

In [11]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[-1,:]),iris.target[-1]))
print('Probabilities for each class from 0 to 2: %s'% logistic.predict_proba(iris.data[-1,:]))

Predicted class [2], real class 2
Probabilities for each class from 0 to 2: [[ 0.00168787  0.28720074  0.71111138]]


/home/bhumihar/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/home/bhumihar/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [12]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[-1,:].reshape(1,-1)),iris.target[-1]))
#print('Probabilities for each class from 0 to 2: %s'% logistic.predict_proba(iris.data[-1,:]))

Predicted class [2], real class 2


/home/bhumihar/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [13]:
X[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [14]:
X.reshape(-1, 1)

array([[ 5.1],
       [ 3.5],
       [ 1.4],
       [ 0.2],
       [ 4.9],
       [ 3. ],
       [ 1.4],
       [ 0.2],
       [ 4.7],
       [ 3.2],
       [ 1.3],
       [ 0.2],
       [ 4.6],
       [ 3.1],
       [ 1.5],
       [ 0.2],
       [ 5. ],
       [ 3.6],
       [ 1.4],
       [ 0.2],
       [ 5.4],
       [ 3.9],
       [ 1.7],
       [ 0.4],
       [ 4.6],
       [ 3.4],
       [ 1.4],
       [ 0.3],
       [ 5. ],
       [ 3.4],
       [ 1.5],
       [ 0.2],
       [ 4.4],
       [ 2.9],
       [ 1.4],
       [ 0.2],
       [ 4.9],
       [ 3.1],
       [ 1.5],
       [ 0.1],
       [ 5.4],
       [ 3.7],
       [ 1.5],
       [ 0.2],
       [ 4.8],
       [ 3.4],
       [ 1.6],
       [ 0.2],
       [ 4.8],
       [ 3. ],
       [ 1.4],
       [ 0.1],
       [ 4.3],
       [ 3. ],
       [ 1.1],
       [ 0.1],
       [ 5.8],
       [ 4. ],
       [ 1.2],
       [ 0.2],
       [ 5.7],
       [ 4.4],
       [ 1.5],
       [ 0.4],
       [ 5.4],
       [ 3.9],
       [ 1

In [15]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [16]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data[:5,:], iris.target[:-1]
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [17]:
iris_iridata

NameError: name 'iris_data' is not defined

In [18]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [19]:
iris.data[-1,:].reshape(-1,1)

array([[ 5.9],
       [ 3. ],
       [ 5.1],
       [ 1.8]])

In [20]:
iris.data[-1,:].reshape(1,-1)

array([[ 5.9,  3. ,  5.1,  1.8]])

In [21]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[-1,:]),iris.target[-1]))
#print('Probabilities for each class from 0 to 2: %s'% logistic.predict_proba(iris.data[-1,:]))

ValueError: Found input variables with inconsistent numbers of samples: [5, 149]

In [22]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[-1,:]),iris.target[-1]))
#print('Probabilities for each class from 0 to 2: %s'% logistic.predict_proba(iris.data[-1,:]))

ValueError: Found input variables with inconsistent numbers of samples: [5, 149]

In [23]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data[:-1,:], iris.target[:-1]
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[-1,:]),iris.target[-1]))

SyntaxError: invalid character in identifier (<ipython-input-23-8397ec4a8619>, line 3)

In [24]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data[:-1,:], iris.target[:-1]
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[-1,:].reshape(1,-1)),iris.target[-1]))

Predicted class [2], real class 2


/home/bhumihar/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [25]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data[:-1,:], iris.target[:-1]
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(iris.data[-1,:].reshape(1,-1)),iris.target[-1]))

Predicted class [2], real class 2


In [26]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:5000,1:]
y = train_m[:5000,0]
logistic = LogisticRegression()
logistic.fit(X,y)
print ('Predicted class %s, real class %s' % (logistic.predict(X[419,:].reshape(1,-1)),y[419]))

Predicted class [6], real class 6


In [27]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:5000,1:]
y = train_m[:5000,0]
logistic = LogisticRegression()
logistic.fit(X,y)
test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:,:]
print ('Predicted class %s' % (logistic.predict(t_X[4189,:].reshape(1,-1))))

Predicted class [0], real class 0


In [28]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
test_df = pd.read_csv('test.csv')
test_m = train_df.as_matrix()
t_X = train_m[:,:]

In [29]:
len(X[:,1])

28000

In [30]:
from sklearn.datasets import load_digits
digits = load_digits()
X, y = digits.data[:1700,:], digits.target[:1700]
tX, ty = digits.data[1700:,:], digits.target[1700:]

In [31]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OneVsOneClassifier
OVR = OneVsRestClassifier(LogisticRegression()).fit(X,y)
OVO = OneVsOneClassifier(LogisticRegression()).fit(X,y)
print ('One vs rest accuracy: %.3f' % OVR.score(tX,ty))
print ('One vs one accuracy: %.3f' % OVO.score(tX,ty))

One vs rest accuracy: 0.948
One vs one accuracy: 0.969


In [32]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:5000,1:]
y = train_m[:5000,0]
logistic = LogisticRegression()
logistic.fit(X,y)
test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:200,:]
print ('Predicted class %s' % (logistic.predict(t_X)))

Predicted class [9]


In [33]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:5000,1:]
y = train_m[:5000,0]
logistic = LogisticRegression()
logistic.fit(X,y)
test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:200,:]
print (logistic.predict(t_X))

[2 0 9 9 3 7 0 3 0 3 5 2 4 0 4 0 3 1 9 0 9 1 1 5 7 4 2 7 8 7 9 5 4 2 6 2 5
 5 1 6 7 7 4 9 8 7 9 8 6 1 6 8 8 3 8 2 1 2 3 5 3 1 7 0 0 0 1 9 0 1 6 5 8 8
 2 8 8 9 2 3 2 8 1 0 9 2 4 3 6 7 2 0 6 6 8 9 3 9 7 4 0 3 2 0 7 3 0 5 0 3 0
 0 9 7 1 7 1 1 8 8 3 7 2 1 6 3 8 7 8 4 3 5 5 0 0 0 3 1 5 0 4 3 4 5 5 8 7 7
 2 0 4 3 5 6 5 3 7 5 7 8 3 0 4 5 1 3 7 6 4 0 2 7 8 6 1 3 7 9 1 2 4 3 8 6 4
 9 2 1 6 0 6 8 4 9 6 0 8 7 5 9]


In [34]:
import numpy as np
ids = np.arange(200)

AttributeError: module 'numpy' has no attribute 'arrange'

In [35]:
import numpy as np
ids = np.arange(200)

In [36]:
ids

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [37]:
import csv
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

ids = np.arange(200)

train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:5000,1:]
y = train_m[:5000,0]

logistic = LogisticRegression()
logistic.fit(X,y)

test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:200,:]

label = logistic.predict(t_X)
predictions_file = open("imagePredict.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["ImageId","Predict"])
open_file_object.writerows(zip(ids, predict))
predictions_file.close()
print ('Done.')

NameError: name 'predict' is not defined

In [38]:
label = logistic.predict(t_X)
predictions_file = open("imagePredict.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["ImageId","Predict"])
open_file_object.writerows(zip(ids, label))
predictions_file.close()
print ('Done.')

Done.


In [39]:
ids = np.arange(200)+1

In [40]:
ids

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [41]:
import csv
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

ids = np.arange(200)

train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:,1:]
y = train_m[:,0]

logistic = LogisticRegression()
logistic.fit(X,y)

test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:200,:]


label = logistic.predict(t_X)
predictions_file = open("imagePredict.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["ImageId","Label"])
open_file_object.writerows(zip(ids, label))
predictions_file.close()
print ('Done.')

Done.


In [42]:
import csv
import numpy as np
import pandas as pd

test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:,:]

ids = np.arange(len(t_X[:,1]))+1

label = logistic.predict(t_X)
predictions_file = open("imagePredict.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["ImageId","Label"])
open_file_object.writerows(zip(ids, label))
predictions_file.close()
print ('Done.')

Done.


In [43]:
import csv
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

ids = np.arange(200)

train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:,1:]
y = train_m[:,0]

logistic = LogisticRegression()
logistic.fit(X,y)

test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:,:]

ids = np.arange(len(t_X[:,1]))+1

label = logistic.predict(t_X)
predictions_file = open("imagePredict.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["ImageId","Label"])
open_file_object.writerows(zip(ids, label))
predictions_file.close()
print ('Done.')

Done.


In [44]:
import csv
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

train_df = pd.read_csv('train.csv')
train_m = train_df.as_matrix()
X = train_m[:,1:]
y = train_m[:,0]

logistic = LogisticRegression()
logistic.fit(X,y)

test_df = pd.read_csv('test.csv')
test_m = test_df.as_matrix()
t_X = test_m[:,:]

ids = np.arange(len(t_X[:,1]))+1

label = logistic.predict(t_X)
predictions_file = open("imagePredict.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["ImageId","Label"])
open_file_object.writerows(zip(ids, label))
predictions_file.close()
print ('Done.')

Done.
